=== ana-polo/LMSGI-E01-Email/solucion/XMLSchema/matrioska/LMSGI-E01-Email-XMLSchema-matrioska.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema" >

	<xs:annotation>
		<xs:documentation xml:lang  = "es-es" >
			<fichero>LMSGI-E01-Email-XMLSchema-matrioska</fichero>
			<fechaCreacion>24-01-2023</fechaCreacion>
			<autor>Ana Polo Arozamena</autor>
			<aplicación>
				Ejemplo de uso de XSD diseñado por el método de matrioska.
			</aplicación>
			<utilidad>Vocabulario para la validación de ficheros básicos de información
				      de los mensajes de las cuentas de correos que hay en un gestor.
			</utilidad>
		</xs:documentation>
	</xs:annotation>

	<!-- ************** -->
	<!-- TIPOS DE DATOS -->
	<!-- ************** -->

	<xs:element name = "cuenta" >
		<xs:complexType>
			<xs:sequence>
				<xs:element name = "descripcion" type = "xs:string" />
				<xs:element name = "email" maxOccurs = "unbounded" >
					<xs:complexType>
						<xs:sequence>
							<xs:element name = "informacion" >
								<xs:complexType>
									<xs:sequence>
										<xs:element name = "categorizar" type = "xs:string" />
									</xs:sequence>
									<xs:attribute name = "codigoEmail" type = "xs:integer"
										use = "required" />
									<xs:attribute name = "leido" use = "required" />
								</xs:complexType>
							</xs:element>
							<xs:element name = "cabecera" >
								<xs:complexType>
									<xs:sequence>
										<xs:element name = "fechaHora" type = "xs:dateTime" />

										<xs:element name = "remitente" >
											<xs:complexType>
												<xs:sequence>
													<xs:element name = "nombre" minOccurs = "0"
														type = "xs:string" />
													<xs:element name = "correo" type = "xs:string" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name = "destinatarios" >
											<xs:complexType>
												<xs:sequence>
													<xs:element name = "destinatario"
														maxOccurs = "unbounded" >
														<xs:complexType>
															<xs:sequence>
																<xs:element name = "nombre"
																	minOccurs = "0" type = "xs:string" />
																<xs:element name = "correo"
																	type = "xs:string" />
																<xs:element name = "tipo"
																	type = "xs:string" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name = "mensaje" type = "xs:string" />
						</xs:sequence>
						<xs:attribute name = "prioridad" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name = "codigoCuenta" type = "xs:integer" use = "required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ana-polo/LMSGI-E01-Email/solucion/XMLSchema/matrioska/LMSGI-E01-Email-XML-XSD.xml
<?xml version = "1.0" encoding = "utf-8" standalone = "no" ?>

<!-- Ejemplar: cuenta -->

<cuenta xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation = "LMSGI-E01-Email-XMLSchema-matrioska.xsd"
		codigoCuenta = "123" >

	<descripcion>micuenta@gmail.com</descripcion>

	<!-- Detalle de cada email.
		Es conveniente es hacer al menos dos para comprobar que la validación de la cardinalidad funciona bien.
		Para probar la opcionalidad del atributo prioridad, os recomiendo hacer un email con ese atributo y otro sin él
		Lo mismo se puede aplicar al resto de elementos opcionales
	-->

	<email prioridad  = "alta" >
		<informacion codigoEmail = "222" leido  = "si" >
			<categorizar>FAMILIA</categorizar>
		</informacion>

		<cabecera>
			<fechaHora>2023-12-31T12:00:01</fechaHora>

			<remitente>
				<nombre>Juana Pérez</nombre>
				<correo>calamidad@gmail.com</correo>
			</remitente>

			<destinatarios>
				<destinatario>
					<nombre>Jose López</nombre>
					<correo>pepito@gmail.com</correo>
					<tipo>Para</tipo>
				</destinatario>

				<destinatario>

					<!-- Compruebo que el nombre es opcional no poniendole
						<nombre>Jaime López</nombre>
					-->

					<correo>jaimito@gmail.com</correo>
					<tipo>CC</tipo>
				</destinatario>
			</destinatarios>
		</cabecera>

		<mensaje>Hola, ¿qué tal?</mensaje>
	</email>

	<email>
		<informacion codigoEmail = "333" leido  = "no" >
			<categorizar>FAMILIA</categorizar>
		</informacion>

		<cabecera>
			<fechaHora>2023-12-31T12:00:01</fechaHora>

			<remitente>
				<correo>calamidad@gmail.com</correo>
			</remitente>

			<destinatarios>
				<destinatario>
					<nombre>Jose López</nombre>
					<correo>pepito@gmail.com</correo>
					<tipo>Para</tipo>
				</destinatario>

				<destinatario>

					<!-- Compruebo que el nombre es opcional no poniendole
						<nombre>Jaime López</nombre>
					-->
					<correo>jaimito@gmail.com</correo>
					<tipo>CC</tipo>
				</destinatario>
			</destinatarios>
		</cabecera>

		<mensaje>Bien, ¿quedamos?</mensaje>
	</email>

</cuenta>
